# Generated by Django 4.1.7 on 2023-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_hod', models.CharField(max_length=50)),
                ('dept_location', models.CharField(choices=[('C-Block', 'Computer Block'), ('M-Block', 'Mechanical Block'), ('R&D Block', 'R&D Block')], max_length=50)),
            ],
            options={
                'db_table': 'department_table',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_dob', models.DateField()),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=100, unique=True)),
                ('emp_contactno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Prefer not to say')], max_length=10)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(unique=True)),
                ('location', models.CharField(max_length=100)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
    ]
